### ISSUE TITLE
How to convert a device token from `Data` to `NSString *`?

### ISSUE THREAD

**Issue by dirtyhenry** [twilio/mobile-sdk-sample-ios#64]
Here is a signature of TwilioAuth in version 1.2.5:

```objc
/**
 * Asynchronously registers the device with the remote Authy server and associates it with the provided registrationToken.
 * @param registrationToken The registration token generated from the backend. It will be used as a proof that the device being registered is who claims to be.
 * @param pushToken         [Optional] This is the token used by APNS to send push notifications to the device.
 * @param completion        Callback when the Authy server responds the request. If the registration was successful, returns an empty NSError. If the registration wasn't successful, returns a non-empty NSError.
 */
- (void)registerDeviceWithRegistrationToken:(NSString * _Nonnull)registrationToken pushToken:(NSString * _Nullable)pushToken completion:(void (^ _Nonnull)(NSError * _Nullable error))completion;
```

It expects pushToken to be a `NSString *`.

This does not match what iOS provides:

```
optional func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data)
```

How to match this `Data` to a `NSString *`?

The naive solution of encoding the data to `.utf8` throws most of the time.

I ended up using this code but I have no guarantee this works:

```    
var deviceTokenAsString: String? {
    return deviceToken.map { String(format: "%02x", $0) }.joined()
}
```
(where `deviceToken` is of type `Data`, untouched from what the application delegate receives)

Could the framework add a signature accepting a data value? Or can the docs provide an official translation from `Data` to `NSString *` that is supported by the framework?

**Comment by AdrianaPineda** [comment]
hey @dirtyhenry you can try how the sample app does it: https://github.com/twilio/mobile-sdk-sample-ios/blob/master/TwilioAuthSample/AppDelegate.m#L160

**Comment by sanarroya** [comment]
Hi @dirtyhenry the code you're using is good, the implementation we have in our AppDelegate is old and won't work if the project is compiled using Xcode 11 and iOS 13 SDK, you can find more information about this in [this NSHipster article](https://nshipster.com/apns-device-tokens/), we will update our AppDelegate in the future

**Comment by dirtyhenry** [comment]
Another question though: should we use the older method in iOS versions lower than 13?

ie, quoting the same NSHipster article:

```
// ⚠️ Warning: Don't do this (unless running a version lower than iOS 13?)
let tokenData = deviceToken as NSData
let token = "\(tokenData)".replacingOccurrences(of: " ", with: "")
                          .replacingOccurrences(of: "<", with: "")
                          .replacingOccurrences(of: ">", with: "")
```
